from datetime import datetime

from OKE.export.manifest_builder import ManifestBuilder


class ReadmeGenerator:

    def __init__(self):

        self.manifest = ManifestBuilder()

    def build(self):

        manifest = self.manifest.build()

        project = manifest["project"]
        counts = manifest["counts"]

        lines = [

            f"# {project['full_name']}",
            "",

            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",

            "---",
            "",

            "## Overview",
            "",
            f"**Project:** {project['name']}",
            f"**Type:** {project['type']}",
            f"**Primary Language:** {project['primary_language']}",
            "",

            "---",
            "",

            "## Current Status",
            "",
            f"- Architecture : {manifest['status']['architecture']}",
            f"- Foundation  : {manifest['status']['foundation']}",
            f"- Export      : {manifest['status']['export_system']}",
            "",

            "---",
            "",

            "## Inventory",
            "",
            f"- Commands : {counts['commands']}",
            f"- Specialists : {counts['specialists']}",
            f"- Builders : {counts['builders']}",
            f"- Analyzers : {counts['analyzers']}",
            f"- Pipelines : {counts['pipelines']}",
            f"- Services : {counts['services']}",
            "",

            "---",
            "",

            "## Purpose",
            "",
            "OKE is the Engineering Operating System behind OPSCORE.",
            "",
            "Its responsibilities include:",
            "",
            "- Engineering analysis",
            "- Architecture review",
            "- Source export",
            "- Regression tracking",
            "- Engineering documentation",
            "- Knowledge preservation",
            "",

            "---",
            "",

            "Generated by OKE Export System",
            ""
        ]

        return "\n".join(lines)